//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by instnp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INSTNP_DIALOG               102
#define IDS_OSERR                       102
#define IDS_APP_RUNNING                 103
#define IDS_SERVICEINSTALLED            104
#define IDS_INSTSERVICEFAILED           105
#define IDS_SERVICEDELETED              106
#define IDS_SERVICEDELETEFAILED         107
#define IDS_DRIVINSTALLED               108
#define IDS_DRIVINSTFAILED              109
#define IDS_NONPCOMM                    110
#define IDS_NODRIVER                    111
#define IDS_DRIVSTARTFAILED             112
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       131
#define IDC_INSTALL                     1000
#define IDC_DEINSTALL                   1001
#define IDC_START                       1002
#define IDC_STOP                        1003
#define IDC_INSTALLSERVICE              1004
#define IDC_MESSAGE                     1005
#define IDC_PPORTNAME                   1006
#define IDC_AUTOSTART                   1007
#define IDC_DEINSTALLSERVICE            1008
#define IDC_PATHCHANGE                  1009
#define IDC_PPORTNAME1                  1010
#define IDC_PPORTNAME2                  1011
#define IDC_DRVPATH                     1012
#define IDC_ISSERVICE                   1013
#define IDC_EXTRAARGUMENTS              1014
#define IDC_NPCOMM                      1015
#define IDC_NPCOMM1                     1016
#define IDC_NPCOMM2                     1017
#define IDC_SERVICEFRAME                1018
#define IDC_DRIVERFRAME                 1019
#define IDC_PNAME                       1020
#define IDC_PNAME1                      1021
#define IDC_PNAME2                      1022
#define IDC_ARGLABEL                    1023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
